# Generated by Django 6.0.2 on 2026-03-05 01:58

import django_mongodb_backend.fields
import riskapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', django_mongodb_backend.fields.EncryptedCharField(max_length=200)),
                ('description', django_mongodb_backend.fields.EncryptedCharField(blank=True, default='', max_length=500)),
                ('category', django_mongodb_backend.fields.EmbeddedModelField(embedded_model=riskapp.models.RiskCategory)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RiskCategory',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', django_mongodb_backend.fields.EncryptedCharField(max_length=100)),
                ('description', django_mongodb_backend.fields.EncryptedCharField(blank=True, max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RiskOwner',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', django_mongodb_backend.fields.EncryptedCharField(max_length=150)),
                ('email', django_mongodb_backend.fields.EncryptedCharField(blank=True, max_length=254)),
                ('role', django_mongodb_backend.fields.EncryptedCharField(blank=True, max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk', django_mongodb_backend.fields.EmbeddedModelField(embedded_model=riskapp.models.Risk)),
                ('owner', django_mongodb_backend.fields.EmbeddedModelField(blank=True, embedded_model=riskapp.models.RiskOwner, null=True)),
                ('likelihood', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=10)),
                ('impact', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=10)),
                ('score', models.PositiveSmallIntegerField()),
                ('assessed_on', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'risk_assessments',
                'ordering': ['-assessed_on'],
                'indexes': [models.Index(fields=['likelihood'], name='risk_assess_likelih_bce01a_idx'), models.Index(fields=['impact'], name='risk_assess_impact_2c62f9_idx'), models.Index(fields=['score'], name='risk_assess_score_a7f13e_idx')],
            },
        ),
    ]
